version: '3'
services:
  mkdocs:
    image: nginx:latest
    container_name: mkdocs
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 9090:80
    volumes:
      - ./docs/.vitepress/dist:/usr/share/nginx/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf